### ISSUE TITLE
FIPS mode prevents subsequent package installation due to strict SSL certificate authority validation

### ISSUE THREAD

**Issue by scattana** [RedHatGov/rhel8-stig-latest#79]
STIG requirements dictate FIPS mode is enabled (fix no. 7 from the script: enable_fips_mode). However, after FIPS is enabled, _yum_ fails to download or update any subsequent packages that use RSA 2048-bit TLS/SSL validation. This is an issue with many public cloud vendors and results in the following error:

`Error: Error downloading packages:
Curl error (60): Peer certificate cannot be authenticated with given CA certificate for https://cds.rhel.updates.googlecloud.com/pulp/mirror//content/dist/rhel8/rhui/8/x86_64/appstream/os [SSL certificate problem: CA signature digest algorithm too weak`

Is there a known workaround other than disabling FIPS? It seems like the issue comes from the vendor image - in this case, Google Cloud - not using a FIPS-compliant algorithm.

**Comment by isimluk** [comment]
I am afraid there is no workaround. FIPS is designed to shield exactly against alike scenarios where software modules would be transferred over through weaker cypher.
