### ISSUE TITLE
If usbguard is a part of a profile, the generate section tries to remediate UBI8 containers.

### ISSUE THREAD

**Issue by younkfunk** [RedHatGov/rhel8-stig-latest#83]
Trying to use the xccdf_org.ssgproject.content_profile_stig profile in ssg-rhel8-ds.xml and when it generates the remediations, only 2 of the 6 scripts treat containers as not applicable. If used in an automated build, this will break the build as you cannot install usbguard on a UBI8 container. It is not included in the UBI repo from Red Hat.

Identifier CCE-82959-8: 
xccdf_org.ssgproject.content_rule_package_usbguard_installed

If you dig into the xml file - 4 of the rules only grep for s390x:
if ! grep -q s390x /proc/sys/kernel/osrelease; then

Two of the rules actually look to see if it's a container as well:
if ! grep -q s390x /proc/sys/kernel/osrelease &amp;&amp; { [ ! -f /.dockerenv ] &amp;&amp; [ ! -f /run/.containerenv ]; }; then

If any of those are true, the "Remediation is not applicable" and I believe that this container query should be on all of the usbguard related rules.  It seems like this is geared towards workstations and servers - and not containers. Otherwise, this package should be made available in the Red Hat Universal Base Image 8 repos.

With the default repos, you get: Error: Unable to find a match: usbguard

**Comment by younkfunk** [comment]
I know this may not be the right place to address this? Not sure exactly where if this is not. If someone can please direct me I'd appreciate it. Thanks

**Comment by ggbecker** [comment]
You found the correct place, you may close this one: https://github.com/ComplianceAsCode/content/issues/8248

**Comment by younkfunk** [comment]
Closed the other one - it had more data but it's still there for reference.

I did prove out that RHEL seems to be the only flavor with their own UBI Stream. All others allowed the download of USBGuard (Alma, Rocky, CentOS...) I still believe that containers should not be applicable.

**Comment by younkfunk** [comment]
I miss understood the mentions... sorry will fix
